export { default as createCharacterGateway } from './character'
export type { CharacterGateway } from './character'
export { default as createChatGateway } from './chat'
export type { ChatGateway } from './chat'
export { default as createAiGateway } from './ai'
export type { AiGateway, AiChatMessage, AiClientConfig, ChatCompletionParams } from './ai'
export { default as createWorldbookGateway } from './worldbook'
export type { WorldbookGateway } from './worldbook'
export { default as createConfigGateway } from './config'
export type { ConfigGateway } from './config'
export { default as createEventGateway } from './event'
export type { EventGateway } from './event'
export { default as createVectorGateway } from './vector'
export type { VectorGateway } from './vector'
export { default as createFileStorageGateway } from './file-storage'
export type { FileStorageGateway } from './file-storage'
export { getHostContext } from './host-context'
