export const MSG_FIELD_PREFIX = 'CN_'

export const FRAME_FIELD_PREFIX = `${MSG_FIELD_PREFIX}FRAME_`

export const RECALL_FIELD_PREFIX = `${MSG_FIELD_PREFIX}RECALL`

export const KEYWORDS_FIELD_PREFIX = `${MSG_FIELD_PREFIX}KEYWORDS_`
